### ISSUE TITLE
Issue with dependency_tree

### ISSUE THREAD

**Issue by ad-on-is** [Julien-R44/hot-hook#9]
Hi, 

I'm the developer of [Adonis AutoSwagger](https://github.com/ad-on-is/adonis-autoswagger)
I've recently implemented autogeneration for adonisJS validators.

However, when `node ace serve --hmr` is used, it breaks the functionality of my library.

```
Error: Node /home/adonis/.local/tmp/adonis-test-file/server/app/validators/comment.ts does not exist
    at DependencyTree.getVersion (file:///home/adonis/.local/tmp/adonis-test-file/server/node_modules/.pnpm/hot-hook@0.2.6/node_modules/hot-hook/build/src/dependency_tree.js:26:19)
    at HotHookLoader.resolve (file:///home/adonis/.local/tmp/adonis-test-file/server/node_modules/.pnpm/hot-hook@0.2.6/node_modules/hot-hook/build/src/loader.js:169:46)
    at async nextResolve (node:internal/modules/esm/hooks:750:22)
    at async Hooks.resolve (node:internal/modules/esm/hooks:238:24)
    at async handleMessage (node:internal/modules/esm/worker:199:18)
```

Here's a simplified example, how the integration works.

adonisJS routes.ts
```ts
router.get('/swagger', async () => {
  return AutoSwagger.default.docs(router.toJSON(), swagger)
})
```
Adonis AutoSwagger then automatically imports all files from the adonisJS projects `app/validators/**/*.ts` folder

```ts

// files reads the root folder of the adonisjs project and gets all files from app/validators/*.ts

for (let file of files) {
        if (/^[a-zA-Z]:/.test(file)) {
          file = "file:///" + file;
        }
        const val = await import(file);
        for (const [key, value] of Object.entries(val)) {
          if (value.constructor.name.includes("VineValidator")) {
            validators[key] = await this.validatorParser.validatorToObject(
              value as VineValidator<any, any>
            );
            validators[key].description = key + " (Validator)";
          }
        }
      }
```
And here's the issue... hot-hook throws an error, that the file does not exist, but it does.

Is there anything I can fix on my side here? Or is it an upstream issue?

**Comment by Julien-R44** [comment]
Hi, could you provide a simplified reproduction please?

**Comment by ad-on-is** [comment]
Oh sure...
https://github.com/ad-on-is/adonisjs-hothook-issue

- Check out repo
- cd into server
- Run '(p)npm -i'
- Run '(p)npm run dev
- Visit http://localhost:3333/swagger

**Comment by ad-on-is** [comment]
Hey @Julien-R44 just wanted to ask if you found time to look into this issue or whether you need any further info from my side?

**Comment by Julien-R44** [comment]
Hey, sorry I've been super busy these last few weeks. Thanks for the repro I'll try to look at it asap

**Comment by Julien-R44** [comment]
Hey, sorry for the late reply! 

after some investigation, I believe the problem is adonis-autoswagger is using CommonJS modules. Can you try with an ESM build and see what happens?
